services:
  backend:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    container_name: json_viewer_backend
    env_file: .env
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
