export const exampleJsonData: Record<string, string> = {
  ecommerce: JSON.stringify({
    catalog: {
      metadata: {
        totalProducts: 15,
        lastUpdated: "2025-08-03T10:30:00Z",
        currency: "USD",
        storeId: "store_main_001",
      },
      categories: [
        {
          id: "cat_electronics",
          name: "Electronics",
          subcategories: ["Audio", "Computing", "Mobile", "Gaming"],
        },
        {
          id: "cat_clothing",
          name: "Clothing",
          subcategories: ["Men", "Women", "Kids", "Accessories"],
        },
        {
          id: "cat_home",
          name: "Home & Garden",
          subcategories: ["Furniture", "Appliances", "Decor", "Tools"],
        },
        {
          id: "cat_books",
          name: "Books",
          subcategories: ["Fiction", "Non-fiction", "Technical", "Children"],
        },
        {
          id: "cat_sports",
          name: "Sports & Outdoors",
          subcategories: ["Fitness", "Outdoor", "Team Sports", "Water Sports"],
        },
      ],
      products: [
        {
          id: "prod_001",
          sku: "WBH-2024-BLK",
          name: "Wireless Bluetooth Headphones",
          category: "cat_electronics",
          subcategory: "Audio",
          brand: "AudioTech",
          price: 89.99,
          originalPrice: 129.99,
          discount: 30.77,
          inStock: true,
          inventory: 45,
          reserved: 3,
          sold: 234,
          rating: 4.5,
          reviewCount: 127,
          specifications: {
            batteryLife: "30 hours",
            chargingTime: "2 hours",
            weight: "250g",
            connectivity: ["Bluetooth 5.0", "USB-C", "3.5mm Jack"],
            features: ["noise-canceling", "water-resistant", "foldable"],
            colors: ["black", "white", "blue", "red"],
            warranty: "2 years",
          },
          dimensions: {
            length: 20.5,
            width: 18.0,
            height: 8.5,
            unit: "cm",
          },
          tags: ["wireless", "noise-canceling", "portable", "premium"],
          releaseDate: "2024-03-15T00:00:00Z",
          supplier: {
            id: "sup_001",
            name: "Global Electronics Supply",
            location: "Shanghai, China",
            leadTime: 14,
          },
        },
        {
          id: "prod_002",
          sku: "LAP-UB-15-SLV",
          name: "UltraBook Pro 15",
          category: "cat_electronics",
          subcategory: "Computing",
          brand: "TechCorp",
          price: 1299.99,
          originalPrice: 1599.99,
          discount: 18.75,
          inStock: true,
          inventory: 23,
          reserved: 5,
          sold: 89,
          rating: 4.8,
          reviewCount: 56,
          specifications: {
            processor: "Intel Core i7-1355U",
            ram: "16GB DDR4",
            storage: "512GB NVMe SSD",
            display: "15.6 inch 4K OLED",
            graphics: "Intel Iris Xe",
            operatingSystem: "Windows 11 Pro",
            ports: ["USB-C x2", "USB-A x2", "HDMI 2.1", "SD Card"],
            batteryLife: "12 hours",
            weight: "1.8kg",
          },
          dimensions: {
            length: 35.8,
            width: 24.2,
            height: 1.9,
            unit: "cm",
          },
          tags: ["laptop", "ultrabook", "professional", "4K"],
          releaseDate: "2024-01-10T00:00:00Z",
        },
        {
          id: "prod_003",
          sku: "TS-CTN-BLU-M",
          name: "Cotton T-Shirt",
          category: "cat_clothing",
          subcategory: "Men",
          brand: "ComfortWear",
          price: 24.99,
          originalPrice: 34.99,
          discount: 28.58,
          inStock: true,
          inventory: 150,
          reserved: 10,
          sold: 567,
          rating: 4.3,
          reviewCount: 234,
          sizes: ["XS", "S", "M", "L", "XL", "XXL"],
          colors: ["blue", "white", "black", "gray", "navy"],
          material: "100% Organic Cotton",
          careInstructions: "Machine wash cold, tumble dry low",
          tags: ["casual", "cotton", "comfortable", "basic"],
        },
        {
          id: "prod_004",
          sku: "DRN-TECH-4K",
          name: "SkyMaster Drone 4K",
          category: "cat_electronics",
          subcategory: "Mobile",
          brand: "AeroTech",
          price: 799.99,
          originalPrice: 999.99,
          discount: 20.0,
          inStock: false,
          inventory: 0,
          reserved: 15,
          sold: 45,
          rating: 4.6,
          reviewCount: 28,
          specifications: {
            camera: "4K HDR 60fps",
            flightTime: "30 minutes",
            range: "5 km",
            features: ["GPS", "Follow Me", "Obstacle Avoidance", "Return Home"],
            weight: "595g",
            maxSpeed: "65 km/h",
            windResistance: "Level 5",
          },
          tags: ["drone", "4K", "aerial", "photography"],
          releaseDate: "2024-02-20T00:00:00Z",
        },
        {
          id: "prod_005",
          sku: "YGA-MAT-ECO",
          name: "Eco-Friendly Yoga Mat",
          category: "cat_sports",
          subcategory: "Fitness",
          brand: "ZenFit",
          price: 45.99,
          originalPrice: 59.99,
          discount: 23.34,
          inStock: true,
          inventory: 78,
          reserved: 2,
          sold: 189,
          rating: 4.7,
          reviewCount: 145,
          specifications: {
            material: "Natural Rubber & Cork",
            thickness: "6mm",
            dimensions: "183cm x 61cm",
            weight: "2.5kg",
            features: ["Non-slip", "Antimicrobial", "Biodegradable"],
            colors: ["natural", "purple", "blue", "green"],
          },
          tags: ["yoga", "fitness", "eco-friendly", "exercise"],
        },
      ],
      promotions: [
        {
          id: "promo_001",
          name: "Summer Sale",
          type: "percentage",
          value: 25,
          applicableCategories: ["cat_clothing", "cat_sports"],
          startDate: "2024-06-01T00:00:00Z",
          endDate: "2024-08-31T23:59:59Z",
          minPurchase: 50,
          code: "SUMMER25",
        },
        {
          id: "promo_002",
          name: "Tech Tuesday",
          type: "fixed",
          value: 50,
          applicableCategories: ["cat_electronics"],
          dayOfWeek: "Tuesday",
          minPurchase: 200,
          code: "TECHTUESDAY",
        },
      ],
      shippingOptions: [
        {
          id: "ship_standard",
          name: "Standard Shipping",
          cost: 5.99,
          estimatedDays: [5, 7],
          trackable: true,
        },
        {
          id: "ship_express",
          name: "Express Shipping",
          cost: 15.99,
          estimatedDays: [2, 3],
          trackable: true,
          insurance: true,
        },
        {
          id: "ship_overnight",
          name: "Overnight Shipping",
          cost: 29.99,
          estimatedDays: [1, 1],
          trackable: true,
          insurance: true,
          signatureRequired: true,
        },
      ],
    },
  }, null, 2),

  userProfile: JSON.stringify({
    user: {
      id: "usr_789456123",
      username: "johndoe",
      email: "john.doe@example.com",
      fullName: "John Michael Doe",
      dateOfBirth: "1990-05-15",
      phoneNumber: "+1-555-0123",
      emailVerified: true,
      twoFactorEnabled: true,
      accountCreated: "2021-03-10T14:30:00Z",
      lastLogin: "2025-08-03T09:15:30Z",
      accountType: "premium",
      subscriptionExpiry: "2025-12-31T23:59:59Z",
      profileImage: "https://api.example.com/users/789456123/avatar.jpg",
      bio: "Software developer, tech enthusiast, coffee lover",
      location: {
        city: "San Francisco",
        state: "California",
        country: "United States",
        timezone: "America/Los_Angeles",
        coordinates: {
          latitude: 37.7749,
          longitude: -122.4194,
        },
      },
      preferences: {
        language: "en-US",
        currency: "USD",
        theme: "dark",
        notifications: {
          email: true,
          push: true,
          sms: false,
          marketing: false,
        },
        privacy: {
          profileVisibility: "friends",
          showEmail: false,
          showPhone: false,
          allowDataCollection: true,
        },
      },
      socialProfiles: [
        {
          platform: "LinkedIn",
          url: "https://linkedin.com/in/johndoe",
          verified: true,
        },
        {
          platform: "GitHub",
          url: "https://github.com/johndoe",
          verified: true,
        },
        {
          platform: "Twitter",
          url: "https://twitter.com/johndoe",
          verified: false,
        },
      ],
      stats: {
        postsCount: 145,
        followersCount: 1234,
        followingCount: 567,
        likesReceived: 3456,
        commentsCount: 789,
        achievementPoints: 2500,
        level: 15,
      },
      achievements: [
        {
          id: "ach_001",
          name: "Early Adopter",
          description: "Joined within the first year",
          unlockedAt: "2021-03-10T14:30:00Z",
          icon: "star",
          rarity: "rare",
        },
        {
          id: "ach_002",
          name: "Contributor",
          description: "Made 100+ contributions",
          unlockedAt: "2023-07-22T10:45:00Z",
          icon: "trophy",
          rarity: "uncommon",
        },
        {
          id: "ach_003",
          name: "Social Butterfly",
          description: "Connected 3+ social accounts",
          unlockedAt: "2022-11-15T16:20:00Z",
          icon: "butterfly",
          rarity: "common",
        },
      ],
      activityHistory: [
        {
          id: "act_001",
          type: "post",
          action: "created",
          timestamp: "2025-08-02T14:30:00Z",
          details: {
            postId: "post_456",
            title: "Understanding TypeScript Generics",
          },
        },
        {
          id: "act_002",
          type: "comment",
          action: "replied",
          timestamp: "2025-08-01T09:15:00Z",
          details: {
            commentId: "comm_789",
            parentPost: "post_123",
          },
        },
        {
          id: "act_003",
          type: "achievement",
          action: "unlocked",
          timestamp: "2025-07-28T12:00:00Z",
          details: {
            achievementId: "ach_004",
            name: "Power User",
          },
        },
      ],
      savedItems: [
        {
          id: "save_001",
          type: "article",
          itemId: "art_789",
          savedAt: "2025-07-15T10:30:00Z",
          tags: ["javascript", "tutorial"],
        },
        {
          id: "save_002",
          type: "video",
          itemId: "vid_456",
          savedAt: "2025-07-10T15:45:00Z",
          tags: ["react", "performance"],
        },
      ],
      paymentMethods: [
        {
          id: "pay_001",
          type: "credit_card",
          last4: "4242",
          brand: "Visa",
          expiryMonth: 12,
          expiryYear: 2027,
          isDefault: true,
        },
        {
          id: "pay_002",
          type: "paypal",
          email: "john.doe@example.com",
          isDefault: false,
        },
      ],
    },
  }, null, 2),

  apiResponse: JSON.stringify({
    status: "success",
    code: 200,
    timestamp: "2025-08-03T14:30:45.123Z",
    requestId: "req_abc123def456",
    data: {
      users: [
        {
          id: 1,
          name: "Alice Johnson",
          email: "alice@example.com",
          role: "admin",
          department: "Engineering",
          isActive: true,
          lastActive: "2025-08-03T14:15:00Z",
          projects: [
            {
              id: "proj_001",
              name: "Website Redesign",
              status: "in_progress",
              completion: 75,
            },
            {
              id: "proj_002",
              name: "Mobile App",
              status: "planning",
              completion: 10,
            },
          ],
        },
        {
          id: 2,
          name: "Bob Smith",
          email: "bob@example.com",
          role: "developer",
          department: "Engineering",
          isActive: true,
          lastActive: "2025-08-03T13:45:00Z",
          projects: [
            {
              id: "proj_001",
              name: "Website Redesign",
              status: "in_progress",
              completion: 75,
            },
          ],
        },
        {
          id: 3,
          name: "Carol White",
          email: "carol@example.com",
          role: "designer",
          department: "Design",
          isActive: false,
          lastActive: "2025-08-01T10:30:00Z",
          projects: [
            {
              id: "proj_003",
              name: "Brand Guidelines",
              status: "completed",
              completion: 100,
            },
          ],
        },
      ],
      pagination: {
        page: 1,
        perPage: 20,
        total: 3,
        totalPages: 1,
        hasNext: false,
        hasPrevious: false,
      },
      metadata: {
        apiVersion: "v2.1.0",
        responseTime: 145,
        serverRegion: "us-west-2",
        cached: false,
      },
    },
    errors: [],
    warnings: [],
  }, null, 2),

  financialReport: JSON.stringify({
    report: {
      company: "Tech Innovations Corp",
      fiscalYear: 2024,
      quarter: "Q2",
      currency: "USD",
      preparedBy: "Finance Department",
      approvedBy: "CFO",
      dateGenerated: "2024-07-15T09:00:00Z",
      summary: {
        totalRevenue: 15750000,
        totalExpenses: 11250000,
        netIncome: 4500000,
        ebitda: 5625000,
        grossMargin: 0.65,
        operatingMargin: 0.32,
        netMargin: 0.286,
      },
      revenue: {
        byProduct: [
          {
            product: "Cloud Services",
            amount: 7500000,
            growth: 0.25,
            percentage: 0.476,
          },
          {
            product: "Software Licenses",
            amount: 4800000,
            growth: 0.15,
            percentage: 0.305,
          },
          {
            product: "Consulting",
            amount: 2700000,
            growth: 0.08,
            percentage: 0.171,
          },
          {
            product: "Support Services",
            amount: 750000,
            growth: -0.05,
            percentage: 0.048,
          },
        ],
        byRegion: [
          {
            region: "North America",
            amount: 8250000,
            countries: ["USA", "Canada", "Mexico"],
            growth: 0.18,
          },
          {
            region: "Europe",
            amount: 4500000,
            countries: ["UK", "Germany", "France", "Spain"],
            growth: 0.22,
          },
          {
            region: "Asia Pacific",
            amount: 2400000,
            countries: ["Japan", "China", "Australia", "India"],
            growth: 0.35,
          },
          {
            region: "Other",
            amount: 600000,
            countries: ["Brazil", "UAE", "South Africa"],
            growth: 0.12,
          },
        ],
        recurring: {
          monthly: 4200000,
          annual: 50400000,
          churnRate: 0.02,
          averageContractValue: 25000,
          customerLifetimeValue: 125000,
        },
      },
      expenses: {
        byCategory: [
          {
            category: "Salaries & Benefits",
            amount: 6750000,
            percentage: 0.6,
            headcount: 125,
          },
          {
            category: "Research & Development",
            amount: 2250000,
            percentage: 0.2,
          },
          {
            category: "Sales & Marketing",
            amount: 1350000,
            percentage: 0.12,
          },
          {
            category: "Operations",
            amount: 675000,
            percentage: 0.06,
          },
          {
            category: "Administrative",
            amount: 225000,
            percentage: 0.02,
          },
        ],
        trends: {
          quarterOverQuarter: 0.08,
          yearOverYear: 0.15,
          projectedNext: 11750000,
        },
      },
      cashFlow: {
        operating: 5250000,
        investing: -1500000,
        financing: -750000,
        netChange: 3000000,
        beginningCash: 8500000,
        endingCash: 11500000,
      },
      balanceSheet: {
        assets: {
          current: {
            cash: 11500000,
            accountsReceivable: 3500000,
            inventory: 500000,
            total: 15500000,
          },
          nonCurrent: {
            propertyPlantEquipment: 4500000,
            intangibleAssets: 2500000,
            investments: 1500000,
            total: 8500000,
          },
          totalAssets: 24000000,
        },
        liabilities: {
          current: {
            accountsPayable: 1500000,
            shortTermDebt: 500000,
            accruedExpenses: 750000,
            total: 2750000,
          },
          nonCurrent: {
            longTermDebt: 3000000,
            deferredRevenue: 1250000,
            total: 4250000,
          },
          totalLiabilities: 7000000,
        },
        equity: {
          commonStock: 10000000,
          retainedEarnings: 7000000,
          totalEquity: 17000000,
        },
      },
      keyMetrics: {
        liquidityRatios: {
          currentRatio: 5.64,
          quickRatio: 5.45,
          cashRatio: 4.18,
        },
        profitabilityRatios: {
          returnOnAssets: 0.188,
          returnOnEquity: 0.265,
          grossProfitMargin: 0.65,
        },
        efficiencyRatios: {
          assetTurnover: 0.656,
          inventoryTurnover: 22.5,
          receivablesTurnover: 4.5,
        },
        leverageRatios: {
          debtToEquity: 0.412,
          debtToAssets: 0.292,
          interestCoverage: 15.0,
        },
      },
      forecast: {
        nextQuarter: {
          revenue: 17250000,
          expenses: 11750000,
          netIncome: 5500000,
          confidence: 0.85,
        },
        yearEnd: {
          revenue: 68500000,
          expenses: 47500000,
          netIncome: 21000000,
          confidence: 0.75,
        },
      },
    },
  }, null, 2),

  configuration: JSON.stringify({
    application: {
      name: "DataProcessor Pro",
      version: "3.2.1",
      environment: "production",
      buildNumber: "20240715-1234",
      releaseDate: "2024-07-15T00:00:00Z",
    },
    server: {
      primary: {
        host: "api.dataprocessor.com",
        port: 443,
        protocol: "https",
        region: "us-west-2",
        loadBalancer: "alb-prod-west-2",
      },
      secondary: {
        host: "api-backup.dataprocessor.com",
        port: 443,
        protocol: "https",
        region: "us-east-1",
        loadBalancer: "alb-prod-east-1",
      },
      healthCheck: {
        endpoint: "/health",
        interval: 30,
        timeout: 10,
        unhealthyThreshold: 3,
      },
    },
    database: {
      primary: {
        type: "postgresql",
        host: "db-primary.internal",
        port: 5432,
        name: "app_production",
        sslMode: "require",
        poolSize: {
          min: 5,
          max: 20,
          idle: 10,
        },
      },
      replica: {
        type: "postgresql",
        host: "db-replica.internal",
        port: 5432,
        name: "app_production",
        readOnly: true,
        sslMode: "require",
      },
      cache: {
        type: "redis",
        host: "cache-cluster.internal",
        port: 6379,
        db: 0,
        ttl: 3600,
        maxMemory: "2gb",
        evictionPolicy: "volatile-lru",
      },
    },
    security: {
      authentication: {
        provider: "oauth2",
        tokenExpiry: 3600,
        refreshTokenExpiry: 2592000,
        multiFactorRequired: true,
        allowedProviders: ["google", "github", "microsoft"],
      },
      encryption: {
        algorithm: "AES-256-GCM",
        keyRotationDays: 90,
        saltRounds: 12,
      },
      cors: {
        enabled: true,
        origins: [
          "https://app.dataprocessor.com",
          "https://admin.dataprocessor.com",
        ],
        methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        allowedHeaders: ["Content-Type", "Authorization", "X-Request-ID"],
        credentials: true,
        maxAge: 86400,
      },
      rateLimit: {
        enabled: true,
        windowMs: 900000,
        maxRequests: 100,
        skipSuccessfulRequests: false,
        keyGenerator: "ip",
      },
    },
    features: {
      analytics: {
        enabled: true,
        provider: "mixpanel",
        trackingId: "mp_abc123def456",
        anonymizeIp: true,
      },
      notifications: {
        enabled: true,
        channels: ["email", "push", "sms", "webhook"],
        queueService: "sqs",
        retryAttempts: 3,
      },
      search: {
        enabled: true,
        provider: "elasticsearch",
        endpoint: "https://search.internal:9200",
        index: "app_production",
        maxResults: 100,
      },
      storage: {
        provider: "s3",
        bucket: "dataprocessor-prod-storage",
        region: "us-west-2",
        encryption: "AES256",
        versioning: true,
        lifecycle: {
          archiveAfterDays: 90,
          deleteAfterDays: 365,
        },
      },
    },
    monitoring: {
      logging: {
        level: "info",
        format: "json",
        destinations: ["cloudwatch", "datadog"],
        retentionDays: 30,
        sensitiveDataMasking: true,
      },
      metrics: {
        enabled: true,
        provider: "datadog",
        apiKey: "dd_key_encrypted",
        customMetrics: true,
        interval: 60,
      },
      alerts: {
        enabled: true,
        channels: ["pagerduty", "slack", "email"],
        rules: [
          {
            metric: "error_rate",
            threshold: 0.01,
            duration: 300,
            severity: "critical",
          },
          {
            metric: "response_time",
            threshold: 1000,
            duration: 600,
            severity: "warning",
          },
        ],
      },
    },
    integrations: {
      payment: {
        provider: "stripe",
        publicKey: "pk_live_encrypted",
        webhookSecret: "whsec_encrypted",
        currency: "USD",
        supportedMethods: ["card", "ach", "wire"],
      },
      email: {
        provider: "sendgrid",
        apiKey: "sg_key_encrypted",
        fromAddress: "noreply@dataprocessor.com",
        templates: {
          welcome: "tmpl_001",
          passwordReset: "tmpl_002",
          invoice: "tmpl_003",
        },
      },
      sms: {
        provider: "twilio",
        accountSid: "AC_encrypted",
        authToken: "auth_encrypted",
        fromNumber: "+15551234567",
      },
    },
    deployment: {
      strategy: "blue_green",
      autoScaling: {
        enabled: true,
        minInstances: 2,
        maxInstances: 10,
        targetCpuUtilization: 70,
        scaleUpCooldown: 300,
        scaleDownCooldown: 600,
      },
      containerization: {
        platform: "kubernetes",
        cluster: "prod-k8s-cluster",
        namespace: "production",
        replicas: 3,
        resources: {
          requests: {
            memory: "512Mi",
            cpu: "500m",
          },
          limits: {
            memory: "1Gi",
            cpu: "1000m",
          },
        },
      },
    },
  }, null, 2),

  geographicData: JSON.stringify({
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        id: "city_001",
        properties: {
          name: "New York City",
          country: "United States",
          countryCode: "US",
          population: 8336817,
          populationDensity: 10933,
          area: 783.8,
          timezone: "America/New_York",
          elevation: 10,
          climate: "Humid subtropical",
          averageTemperature: {
            summer: 25.5,
            winter: 1.5,
            unit: "celsius",
          },
          languages: ["English", "Spanish", "Chinese", "Russian"],
          currency: "USD",
          landmarks: [
            "Statue of Liberty",
            "Central Park",
            "Empire State Building",
            "Times Square",
          ],
        },
        geometry: {
          type: "Point",
          coordinates: [-74.006, 40.7128],
        },
      },
      {
        type: "Feature",
        id: "city_002",
        properties: {
          name: "London",
          country: "United Kingdom",
          countryCode: "GB",
          population: 9002488,
          populationDensity: 5701,
          area: 1579,
          timezone: "Europe/London",
          elevation: 11,
          climate: "Temperate oceanic",
          averageTemperature: {
            summer: 18.7,
            winter: 5.2,
            unit: "celsius",
          },
          languages: ["English"],
          currency: "GBP",
          landmarks: [
            "Big Ben",
            "Tower Bridge",
            "Buckingham Palace",
            "London Eye",
          ],
        },
        geometry: {
          type: "Point",
          coordinates: [-0.1276, 51.5074],
        },
      },
      {
        type: "Feature",
        id: "city_003",
        properties: {
          name: "Tokyo",
          country: "Japan",
          countryCode: "JP",
          population: 13960236,
          populationDensity: 6349,
          area: 2194,
          timezone: "Asia/Tokyo",
          elevation: 40,
          climate: "Humid subtropical",
          averageTemperature: {
            summer: 26.4,
            winter: 5.2,
            unit: "celsius",
          },
          languages: ["Japanese"],
          currency: "JPY",
          landmarks: [
            "Tokyo Skytree",
            "Senso-ji Temple",
            "Imperial Palace",
            "Shibuya Crossing",
          ],
        },
        geometry: {
          type: "Point",
          coordinates: [139.6503, 35.6762],
        },
      },
      {
        type: "Feature",
        id: "route_001",
        properties: {
          name: "Pacific Coast Highway",
          type: "highway",
          designation: "California State Route 1",
          length: 656,
          lengthUnit: "miles",
          countries: ["United States"],
          states: ["California"],
          established: 1934,
          scenicRoute: true,
          averageElevation: 50,
          maxElevation: 1200,
          pointsOfInterest: [
            "Golden Gate Bridge",
            "Big Sur",
            "Monterey Bay",
            "Santa Barbara",
            "Malibu",
          ],
        },
        geometry: {
          type: "LineString",
          coordinates: [
            [-122.4786, 37.8077],
            [-122.4458, 37.7459],
            [-121.8905, 36.6002],
            [-121.7949, 36.3002],
            [-120.658, 35.1428],
            [-119.7029, 34.4208],
            [-118.4912, 34.0195],
          ],
        },
      },
      {
        type: "Feature",
        id: "area_001",
        properties: {
          name: "Central Park",
          type: "park",
          city: "New York City",
          area: 3.41,
          areaUnit: "km²",
          established: 1857,
          visitors: 42000000,
          visitorsUnit: "annual",
          features: [
            "Great Lawn",
            "Reservoir",
            "Zoo",
            "Bethesda Fountain",
            "Strawberry Fields",
          ],
          activities: ["walking", "cycling", "boating", "ice skating"],
        },
        geometry: {
          type: "Polygon",
          coordinates: [
            [
              [-73.9812, 40.7685],
              [-73.9584, 40.7685],
              [-73.9584, 40.8005],
              [-73.9812, 40.8005],
              [-73.9812, 40.7685],
            ],
          ],
        },
      },
      {
        type: "Feature",
        id: "region_001",
        properties: {
          name: "Silicon Valley",
          type: "region",
          country: "United States",
          state: "California",
          majorCities: [
            "San Jose",
            "Palo Alto",
            "Mountain View",
            "Cupertino",
            "Sunnyvale",
          ],
          area: 1854,
          areaUnit: "km²",
          population: 3100000,
          gdp: 535000000000,
          gdpUnit: "USD",
          majorCompanies: ["Apple", "Google", "Meta", "Intel", "Oracle"],
          universities: ["Stanford", "UC Berkeley", "San Jose State"],
        },
        geometry: {
          type: "Polygon",
          coordinates: [
            [
              [-122.4, 37.2],
              [-121.8, 37.2],
              [-121.8, 37.5],
              [-122.4, 37.5],
              [-122.4, 37.2],
            ],
          ],
        },
      },
    ],
    metadata: {
      source: "OpenStreetMap",
      lastUpdated: "2025-08-01T00:00:00Z",
      coordinateSystem: "WGS84",
      projection: "EPSG:4326",
      accuracy: "high",
      license: "ODbL",
    },
    statistics: {
      totalFeatures: 6,
      featureTypes: {
        Point: 3,
        LineString: 1,
        Polygon: 2,
      },
      boundingBox: {
        north: 51.5074,
        south: 34.0195,
        east: 139.6503,
        west: -122.4786,
      },
      totalPopulation: 34299541,
      averageElevation: 115,
    },
  }, null, 2),

  nestedStructure: JSON.stringify({
    organization: {
      name: "Global Tech Solutions",
      founded: 2010,
      headquarters: {
        address: {
          street: "123 Innovation Drive",
          city: "San Francisco",
          state: "California",
          country: "USA",
          postalCode: "94105",
        },
        coordinates: {
          latitude: 37.7749,
          longitude: -122.4194,
        },
        building: {
          floors: 12,
          totalArea: 50000,
          areaUnit: "sqm",
          facilities: {
            cafeteria: {
              capacity: 200,
              operatingHours: {
                weekdays: {
                  open: "07:00",
                  close: "19:00",
                },
                weekends: {
                  open: "09:00",
                  close: "15:00",
                },
              },
              menu: {
                breakfast: ["Continental", "American", "Asian"],
                lunch: ["Salad Bar", "Hot Meals", "Sandwiches"],
                beverages: ["Coffee", "Tea", "Juices", "Soft Drinks"],
              },
            },
            parking: {
              levels: 3,
              totalSpaces: 500,
              reservedSpaces: 50,
              evChargingStations: 20,
              pricing: {
                employee: 0,
                visitor: {
                  hourly: 5,
                  daily: 25,
                },
              },
            },
            gym: {
              area: 500,
              equipment: {
                cardio: ["Treadmills", "Bikes", "Ellipticals"],
                strength: ["Free Weights", "Machines", "Cable Systems"],
                classes: ["Yoga", "Pilates", "HIIT", "Spinning"],
              },
              operatingHours: {
                weekdays: {
                  open: "05:00",
                  close: "22:00",
                },
                weekends: {
                  open: "06:00",
                  close: "20:00",
                },
              },
            },
          },
        },
      },
      departments: {
        engineering: {
          headcount: 250,
          teams: {
            frontend: {
              members: 45,
              lead: "Sarah Johnson",
              technologies: ["React", "Vue", "Angular", "TypeScript"],
              projects: {
                current: [
                  {
                    name: "Customer Portal v2",
                    startDate: "2024-01-15",
                    estimatedCompletion: "2024-09-30",
                    budget: 500000,
                    status: "on_track",
                  },
                  {
                    name: "Mobile App Redesign",
                    startDate: "2024-03-01",
                    estimatedCompletion: "2024-08-15",
                    budget: 300000,
                    status: "at_risk",
                  },
                ],
                completed: [
                  {
                    name: "Dashboard Analytics",
                    completedDate: "2024-02-28",
                    budget: 250000,
                    actualCost: 235000,
                  },
                ],
              },
            },
            backend: {
              members: 60,
              lead: "Michael Chen",
              technologies: ["Node.js", "Python", "Go", "PostgreSQL"],
              infrastructure: {
                servers: {
                  production: 50,
                  staging: 20,
                  development: 30,
                },
                databases: {
                  primary: {
                    type: "PostgreSQL",
                    version: "14.5",
                    size: "2TB",
                  },
                  cache: {
                    type: "Redis",
                    version: "7.0",
                    size: "128GB",
                  },
                },
              },
            },
            devops: {
              members: 25,
              lead: "Alex Rivera",
              tools: ["Kubernetes", "Docker", "Jenkins", "Terraform"],
              metrics: {
                deploymentFrequency: {
                  daily: 12,
                  weekly: 84,
                  monthly: 360,
                },
                leadTime: {
                  average: "2 hours",
                  p50: "1.5 hours",
                  p95: "4 hours",
                },
                mttr: "30 minutes",
                changeFailureRate: 0.02,
              },
            },
          },
        },
        sales: {
          headcount: 75,
          regions: {
            northAmerica: {
              countries: ["USA", "Canada", "Mexico"],
              revenue: {
                q1: 12500000,
                q2: 13750000,
                q3: 14200000,
                q4: 15500000,
              },
              topClients: [
                {
                  name: "TechCorp Inc",
                  contractValue: 2500000,
                  renewalDate: "2024-12-31",
                },
                {
                  name: "Global Systems Ltd",
                  contractValue: 1800000,
                  renewalDate: "2025-03-15",
                },
              ],
            },
            europe: {
              countries: ["UK", "Germany", "France", "Spain", "Italy"],
              revenue: {
                q1: 8500000,
                q2: 9200000,
                q3: 9800000,
                q4: 10500000,
              },
            },
            asiaPacific: {
              countries: ["Japan", "China", "Australia", "India", "Singapore"],
              revenue: {
                q1: 6500000,
                q2: 7200000,
                q3: 8100000,
                q4: 9000000,
              },
            },
          },
        },
      },
      financials: {
        revenue: {
          2022: 85000000,
          2023: 102000000,
          2024: {
            projected: 125000000,
            actual: {
              q1: 27500000,
              q2: 30150000,
              ytd: 57650000,
            },
          },
        },
        expenses: {
          categories: {
            salaries: {
              amount: 45000000,
              percentage: 0.6,
            },
            operations: {
              amount: 15000000,
              percentage: 0.2,
            },
            marketing: {
              amount: 7500000,
              percentage: 0.1,
            },
            research: {
              amount: 7500000,
              percentage: 0.1,
            },
          },
        },
        investments: {
          portfolio: [
            {
              company: "AI Startup Inc",
              amount: 5000000,
              stake: 0.15,
              valuation: 33333333,
            },
            {
              company: "Green Energy Corp",
              amount: 3000000,
              stake: 0.08,
              valuation: 37500000,
            },
          ],
        },
      },
    },
  }, null, 2),

  healthData: JSON.stringify({
    patient: {
      id: "PAT-2024-789456",
      personalInfo: {
        firstName: "Emily",
        lastName: "Thompson",
        dateOfBirth: "1985-06-15",
        age: 39,
        gender: "female",
        bloodType: "O+",
        height: {
          value: 165,
          unit: "cm",
        },
        weight: {
          value: 62,
          unit: "kg",
        },
        bmi: 22.8,
        contactInfo: {
          phone: "+1-555-0199",
          email: "emily.thompson@email.com",
          emergencyContact: {
            name: "James Thompson",
            relationship: "spouse",
            phone: "+1-555-0200",
          },
        },
      },
      medicalHistory: {
        conditions: [
          {
            name: "Hypertension",
            diagnosedDate: "2019-03-10",
            status: "managed",
            medications: ["Lisinopril"],
          },
          {
            name: "Type 2 Diabetes",
            diagnosedDate: "2021-07-22",
            status: "controlled",
            medications: ["Metformin"],
          },
        ],
        allergies: [
          {
            allergen: "Penicillin",
            reaction: "rash",
            severity: "moderate",
          },
          {
            allergen: "Peanuts",
            reaction: "anaphylaxis",
            severity: "severe",
          },
        ],
        surgeries: [
          {
            procedure: "Appendectomy",
            date: "2008-11-15",
            hospital: "General Hospital",
            surgeon: "Dr. Smith",
          },
        ],
        familyHistory: {
          father: ["Heart Disease", "Hypertension"],
          mother: ["Diabetes", "Breast Cancer"],
          siblings: ["None reported"],
        },
      },
      currentVisit: {
        date: "2024-08-03",
        time: "10:30 AM",
        reason: "Annual checkup",
        vitalSigns: {
          bloodPressure: {
            systolic: 128,
            diastolic: 82,
            unit: "mmHg",
            status: "slightly elevated",
          },
          heartRate: {
            value: 72,
            unit: "bpm",
            status: "normal",
          },
          temperature: {
            value: 36.8,
            unit: "celsius",
            status: "normal",
          },
          respiratoryRate: {
            value: 16,
            unit: "breaths/min",
            status: "normal",
          },
          oxygenSaturation: {
            value: 98,
            unit: "%",
            status: "normal",
          },
        },
        labResults: {
          bloodWork: {
            glucose: {
              value: 105,
              unit: "mg/dL",
              range: "70-100",
              status: "slightly elevated",
            },
            cholesterol: {
              total: {
                value: 195,
                unit: "mg/dL",
                range: "<200",
                status: "normal",
              },
              ldl: {
                value: 115,
                unit: "mg/dL",
                range: "<100",
                status: "borderline high",
              },
              hdl: {
                value: 55,
                unit: "mg/dL",
                range: ">40",
                status: "normal",
              },
              triglycerides: {
                value: 125,
                unit: "mg/dL",
                range: "<150",
                status: "normal",
              },
            },
            hemoglobin: {
              value: 13.5,
              unit: "g/dL",
              range: "12-16",
              status: "normal",
            },
            whiteBloodCells: {
              value: 6800,
              unit: "cells/mcL",
              range: "4500-11000",
              status: "normal",
            },
          },
          urinalysis: {
            specificGravity: 1.015,
            ph: 6.5,
            protein: "negative",
            glucose: "negative",
            ketones: "negative",
            blood: "negative",
          },
        },
        assessment: {
          diagnosis: ["Hypertension - controlled", "Type 2 Diabetes - controlled"],
          recommendations: [
            "Continue current medications",
            "Increase physical activity to 150 minutes per week",
            "Follow up with nutritionist",
            "Schedule eye exam",
            "Return in 6 months for follow-up",
          ],
        },
      },
      medications: [
        {
          name: "Lisinopril",
          dosage: "10mg",
          frequency: "once daily",
          startDate: "2019-03-15",
          prescribedBy: "Dr. Johnson",
          refills: 3,
        },
        {
          name: "Metformin",
          dosage: "500mg",
          frequency: "twice daily",
          startDate: "2021-07-25",
          prescribedBy: "Dr. Johnson",
          refills: 2,
        },
        {
          name: "Vitamin D",
          dosage: "2000 IU",
          frequency: "once daily",
          startDate: "2023-01-10",
          prescribedBy: "Dr. Johnson",
          refills: 6,
        },
      ],
      immunizations: [
        {
          vaccine: "COVID-19",
          doses: [
            {
              doseNumber: 1,
              date: "2021-03-15",
              manufacturer: "Pfizer",
            },
            {
              doseNumber: 2,
              date: "2021-04-05",
              manufacturer: "Pfizer",
            },
            {
              doseNumber: "Booster",
              date: "2022-01-20",
              manufacturer: "Pfizer",
            },
          ],
        },
        {
          vaccine: "Influenza",
          date: "2023-10-15",
          manufacturer: "Sanofi",
        },
        {
          vaccine: "Tdap",
          date: "2020-06-10",
          nextDue: "2030-06-10",
        },
      ],
      insurance: {
        provider: "HealthCare Plus",
        policyNumber: "HC789456123",
        groupNumber: "GRP-456789",
        copay: 25,
        deductible: {
          annual: 1500,
          met: 850,
          remaining: 650,
        },
        coverage: {
          medical: true,
          dental: true,
          vision: true,
          prescription: true,
        },
      },
    },
  }, null, 2),
};